[package]
name = "miners_common"
version = "0.1.0"
authors = ["yohandev"]
edition = "2018"

[dependencies]
blockdef = { path = "./src/world/block/blockdef" }
static_assertions = "1.1.0"
parking_lot = "0.11.1"
ptr_meta = "0.1.3"
rayon = "1.5.1"
slab = "0.4.3"
vek = "0.15.1"