[block]
name = "Stairs"
id = "stairs"

[props]
facing = ["north", "south", "east", "west"] # 2 bits
variant = ["oak", "spruce", "birch", "jungle", "acacia", "dark_oak"] # 3 bits

[looks]
geometry = "stairs"
